### ISSUE TITLE
aes key获取失效

### ISSUE THREAD

**Issue by xiedaxia1hao** [forest0/wechat_history_export#3]
你好！请问在执行

`lldb -p $(pgrep WeChat)`

命令的时候，产生如下的报错：

error: attach failed: attach failed (Not allowed to attach to process.  Look in the console messages (Console.app), near the debugserver entries when the attached failed.  The subsystem that denied the attach permission will likely have logged an informative message about why it was denied.)

请问您之前碰见过这样的报错吗？

**Comment by forest0** [comment]
没有遇到过，你试试加个`sudo`，或者在谷歌里搜索下，有效果的话欢迎反馈。

**Comment by xiedaxia1hao** [comment]
> 没有遇到过，你试试加个`sudo`，或者在谷歌里搜索下，有效果的话欢迎反馈。

感谢回复! 我尝试加了sudo，但是没起效果，我再继续研究一下，有进展了过来提个pr

**Comment by xiedaxia1hao** [comment]
过了一段时间找到了解决方案。

在使用lldb的时候，因为mac内置的System Integrity Protection(SIP)存在，使得调试语句都会被系统拒绝。所以在使用这个脚本的时候，需要关闭SIP。

- 检查SIP的状态：
`csrutil status`
如果结果是`System Integrity Protection status: enabled.`的话，我们就需要关闭SIP。

- 关闭 SIP
1. 重启，并在开机的时候按住 Command 和 R
2. 进入恢复模式后进入终端，输入`csrutil disable`
3. 重启生效。

拿到数据库数据库密码以后，再进入恢复模式run`csrutil enable`，就能重新开启SIP了。

希望能帮助到有需要的人。

**Comment by forest0** [comment]
我看了下自己的

```sh
$ csrutil status
System Integrity Protection status: enabled.
```
lldb也是可以正常attach的。

Anyway，thanks for sharing this.
